import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createServer, _resetRateLimitForTests } from "./server.js";
import { analyzeWorkflows } from "./evidenceGap.js";
import { HELP_NOTE, HELP_PAGE, helpUrl, renderExposureReview, REVIEW_SIGN_UP_URL } from "./exposureReview.js";

const wf = (content: string, path = ".github/workflows/deploy.yml") => [{ path, content }];

const UNGATED = `
name: Deploy
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Ship it
        run: helm upgrade --install api ./chart
`;

const BOUND = `
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: AtlaSent gate
        id: gate
        uses: AtlaSent/atlasent-action@v1
        with:
          action: production.deploy
      - name: Deploy
        if: steps.gate.outputs.verified == 'true'
        run: helm upgrade --install api ./chart
`;

const NOTHING = `
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: npm test
`;

describe("renderExposureReview", () => {
  it("states its scope: these files only, not an organizational assessment, and what it cannot see", () => {
    const r = renderExposureReview(analyzeWorkflows(wf(UNGATED)));
    assert.match(r.markdown, /^# Authorization Exposure Review/);
    assert.match(r.markdown, /Free, generated by AtlaSent/);
    assert.match(r.markdown, /It is not an assessment of your organization's authorization posture/);
    assert.match(r.markdown, /nothing was sent anywhere/);
    // Every not_checked line from the analysis is carried, not paraphrased away.
    for (const n of analyzeWorkflows(wf(UNGATED)).not_checked) assert.ok(r.markdown.includes(n), n);
  });

  it("lists each gap with where, why and the exact fix, and offers both help links", () => {
    const report = analyzeWorkflows(wf(UNGATED));
    const r = renderExposureReview(report);
    assert.equal(r.summary.gaps, 1);
    assert.match(r.markdown, /## Steps to fix/);
    assert.match(r.markdown, /`\.github\/workflows\/deploy\.yml:\d+` \(job `deploy`, step "Ship it"\)/);
    assert.match(r.markdown, /```yaml\n[\s\S]*AtlaSent\/atlasent-action/);
    assert.match(r.markdown, /\*\*1 of them has no approval gate that can stop it\.\*\*/);
    assert.equal(r.sign_up_url, REVIEW_SIGN_UP_URL);
    assert.deepEqual(r.help, { explain: helpUrl("explain", 1), rollout: helpUrl("rollout", 1), note: HELP_NOTE });
    assert.ok(r.markdown.includes(helpUrl("explain", 1)));
    assert.ok(r.markdown.includes(helpUrl("rollout", 1)));
  });

  it("help is optional, consent-gated and fee-honest, and names no one", () => {
    assert.match(HELP_NOTE, /^Optional\./);
    assert.match(HELP_NOTE, /only if you ask for that and consent/);
    assert.match(HELP_NOTE, /AtlaSent takes no fee from it/);
    const md = renderExposureReview(analyzeWorkflows(wf(UNGATED))).markdown;
    assert.doesNotMatch(md, /cisco|eugene/i);
  });

  it("links are tagged and carry only the topic and gap count", () => {
    const u = new URL(helpUrl("rollout", 3));
    assert.equal(`${u.origin}${u.pathname}`, HELP_PAGE);
    assert.deepEqual([...u.searchParams.keys()].sort(), ["gaps", "topic", "utm_medium", "utm_source"]);
    assert.equal(u.searchParams.get("utm_source"), "exposure-review");
    assert.equal(u.searchParams.get("gaps"), "3");
    assert.equal(new URL(helpUrl("explain", -2.7)).searchParams.get("gaps"), "0");
    assert.match(REVIEW_SIGN_UP_URL, /utm_source=exposure-review/);
  });

  it("a fully gated repo gets no sign-up push and no help offer", () => {
    const r = renderExposureReview(analyzeWorkflows(wf(BOUND)));
    assert.equal(r.summary.gaps, 0);
    assert.equal(r.help, undefined);
    assert.equal(r.sign_up_url, undefined);
    assert.match(r.markdown, /## Already gated/);
    assert.doesNotMatch(r.markdown, /## Steps to fix/);
    assert.match(r.markdown, /Keep it that way/);
  });

  it("nothing recognized is never reported as safe, and help is still offered", () => {
    const r = renderExposureReview(analyzeWorkflows(wf(NOTHING)));
    assert.match(r.markdown, /That is not proof there are none/);
    assert.ok(r.help);
  });

  it("unreadable files are listed and draw no conclusion", () => {
    const r = renderExposureReview(analyzeWorkflows(wf("jobs: [unclosed", ".github/workflows/broken.yml")));
    assert.match(r.markdown, /## Files that could not be read/);
    assert.match(r.markdown, /`\.github\/workflows\/broken\.yml`/);
    assert.match(r.markdown, /No conclusion is drawn about these files/);
  });

  it("is deterministic", () => {
    const a = renderExposureReview(analyzeWorkflows(wf(UNGATED)));
    const b = renderExposureReview(analyzeWorkflows(wf(UNGATED)));
    assert.equal(a.markdown, b.markdown);
  });
});

describe("atlasent_exposure_review tool", () => {
  async function client() {
    _resetRateLimitForTests();
    const server = createServer();
    const [a, b] = InMemoryTransport.createLinkedPair();
    const c = new Client({ name: "t", version: "0" });
    await Promise.all([server.connect(a), c.connect(b)]);
    return c;
  }

  it("returns the review and makes no network call, with or without an API key", async () => {
    const realFetch = globalThis.fetch;
    let calls = 0;
    globalThis.fetch = (() => {
      calls++;
      throw new Error("network must not be used");
    }) as typeof fetch;
    process.env.ATLASENT_API_KEY = "ask_test_should_not_be_used";
    try {
      const c = await client();
      const res = await c.callTool({ name: "atlasent_exposure_review", arguments: { workflows: wf(UNGATED) } });
      const text = (res.content as Array<{ type: string; text: string }>)[0].text;
      const body = JSON.parse(text);
      assert.equal(body.review, "exposure_review.v1");
      assert.match(body.markdown, /Authorization Exposure Review/);
      assert.equal(body.summary.gaps, 1);
      assert.equal(calls, 0);
    } finally {
      globalThis.fetch = realFetch;
      delete process.env.ATLASENT_API_KEY;
    }
  });

  it("is annotated read-only and closed-world", async () => {
    const c = await client();
    const { tools } = await c.listTools();
    const t = tools.find((x) => x.name === "atlasent_exposure_review");
    assert.ok(t);
    assert.equal(t.annotations?.readOnlyHint, true);
    assert.equal(t.annotations?.openWorldHint, false);
  });
});
