/**
 * atlasent_exposure_review: the free Authorization Exposure Review.
 *
 * Founder decision 2026-10-07 (atlasent-internal DECISION_LEDGER, "Free +
 * advisor services channel"): the Exposure Review is free and self-serve, an
 * AtlaSent product output built from atlasent_evidence_gap_report, never
 * founder or advisor labour. It covers only the workflow files it was given
 * and must say so; it is never presented as an assessment of the reader's
 * whole authorization posture. An independent implementation advisor can be
 * brought in AFTER it, to explain the findings or run the rollout, only
 * through a page where the reader asks for that and consents.
 *
 * Offline and read-only, exactly like the gap report: this module renders
 * analyzeWorkflows() output and makes no network call. The links are plain
 * URLs the reader may choose to open.
 */

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { toolResult } from "./decision.js";
import { analyzeWorkflows, type EvidenceGapReport, type Finding } from "./evidenceGap.js";

const CONSOLE = "https://console.atlasent.io";
const UTM = "utm_source=exposure-review&utm_medium=mcp";
export const REVIEW_SIGN_UP_URL = `${CONSOLE}/auth/sign-up?${UTM}`;
export const HELP_PAGE = `${CONSOLE}/help/implementation`;

export type HelpTopic = "explain" | "rollout";

export function helpUrl(topic: HelpTopic, gaps: number): string {
  return `${HELP_PAGE}?topic=${topic}&gaps=${Math.max(0, Math.trunc(gaps))}&${UTM}`;
}

export interface ExposureReview {
  review: "exposure_review.v1";
  /** The readable review. Markdown. */
  markdown: string;
  summary: EvidenceGapReport["summary"];
  /** Present only when there is something to fix or nothing was recognized. */
  help?: { explain: string; rollout: string; note: string };
  sign_up_url?: string;
}

const STATUS_LABEL: Record<Finding["status"], string> = {
  ungoverned: "No gate",
  weak: "Gate cannot stop it",
  gated: "Gated, not bound",
  gated_upstream: "Gated in an earlier job",
  bound: "Gated and bound",
};

function plural(n: number, one: string, many = `${one}s`): string {
  return `${n} ${n === 1 ? one : many}`;
}

function where(f: Finding): string {
  return `\`${f.workflow}${f.line ? `:${f.line}` : ""}\` (job \`${f.job}\`, step "${f.step}")`;
}

export const HELP_NOTE =
  "Optional. The link opens a request page. AtlaSent shares your details with one independent implementation " +
  "advisor only if you ask for that and consent there. The advisor's work is agreed and paid between you and " +
  "them; AtlaSent takes no fee from it.";

export function renderExposureReview(report: EvidenceGapReport): ExposureReview {
  const s = report.summary;
  const gapFindings = report.findings.filter((f) => f.status === "ungoverned" || f.status === "weak");
  const covered = report.findings.filter((f) => f.status !== "ungoverned" && f.status !== "weak");
  const lines: string[] = [];

  lines.push("# Authorization Exposure Review");
  lines.push("");
  lines.push(
    "Free, generated by AtlaSent from the CI workflow files you supplied. It ran offline: nothing was sent anywhere.",
  );
  lines.push("");

  lines.push("## What this covers, and what it does not");
  lines.push("");
  lines.push(
    `- **Covered:** ${plural(s.workflows_scanned, "workflow file")} read` +
      (s.workflows_unreadable > 0 ? `, ${s.workflows_unreadable} could not be read (listed below).` : "."),
  );
  lines.push(
    "- **Not covered:** this is a review of these files only. It is not an assessment of your organization's " +
      "authorization posture. It cannot see:",
  );
  for (const n of report.not_checked) lines.push(`  - ${n}`);
  lines.push("");

  lines.push("## Summary");
  lines.push("");
  if (report.findings.length === 0) {
    lines.push(
      "No deploy, publish, migration or infrastructure steps were recognized in these files. That is not proof " +
        "there are none: see what this review cannot see, above.",
    );
  } else {
    lines.push(
      `${plural(s.consequential_steps, "step")} can change a real system. ` +
        (s.gaps > 0
          ? `**${plural(s.gaps, "of them has", "of them have")} no approval gate that can stop ${s.gaps === 1 ? "it" : "them"}.**`
          : "Every one has a gate in front of it."),
    );
    lines.push("");
    lines.push("| Status | Steps |");
    lines.push("|---|---|");
    for (const k of ["ungoverned", "weak", "gated", "gated_upstream", "bound"] as const) {
      lines.push(`| ${STATUS_LABEL[k]} | ${s.by_status[k]} |`);
    }
  }
  lines.push("");

  if (gapFindings.length > 0) {
    lines.push("## Steps to fix");
    lines.push("");
    gapFindings.forEach((f, i) => {
      lines.push(`### ${i + 1}. ${STATUS_LABEL[f.status]}: ${f.category}`);
      lines.push("");
      lines.push(`- **Where:** ${where(f)}`);
      lines.push(`- **Why:** ${f.reason}`);
      if (f.confidence === "possible") lines.push("- **Confidence:** possible (a script is called; its contents were not read).");
      if (f.fix?.gate_step) {
        lines.push("- **Add this step before it:**");
        lines.push("");
        lines.push("```yaml");
        lines.push(f.fix.gate_step.trimEnd());
        lines.push("```");
      }
      if (f.fix?.bind_if) lines.push(`- **Then give the step this condition:** \`if: ${f.fix.bind_if}\``);
      if (f.fix?.change) lines.push(`- **Change:** ${f.fix.change}`);
      if (f.fix?.job_permissions) lines.push(`- **Job permissions:** ${f.fix.job_permissions}`);
      if (f.fix?.note) lines.push(`- **Note:** ${f.fix.note}`);
      lines.push("");
    });
  }

  if (covered.length > 0) {
    lines.push("## Already gated");
    lines.push("");
    for (const f of covered) lines.push(`- ${STATUS_LABEL[f.status]}: ${where(f)}`);
    lines.push("");
  }

  if (report.parse_errors.length > 0) {
    lines.push("## Files that could not be read");
    lines.push("");
    for (const e of report.parse_errors) lines.push(`- \`${e.workflow}\`${e.line ? ` line ${e.line}` : ""}: ${e.error}`);
    lines.push("");
    lines.push("No conclusion is drawn about these files.");
    lines.push("");
  }

  const offerHelp = s.gaps > 0 || report.findings.length === 0;
  lines.push("## Next steps");
  lines.push("");
  if (s.gaps > 0) {
    lines.push(
      `1. **Fix it yourself.** Create a free AtlaSent account and API key (${REVIEW_SIGN_UP_URL}), add it as the ` +
        "`ATLASENT_API_KEY` repository secret, make each change above, then run this review again.",
    );
  } else {
    lines.push("1. **Keep it that way.** Run this review again whenever a workflow changes.");
  }
  if (offerHelp) {
    lines.push(
      `2. **Want help?** An independent implementation advisor can walk you through these findings ` +
        `(${helpUrl("explain", s.gaps)}) or roll the gates out with you (${helpUrl("rollout", s.gaps)}). ${HELP_NOTE}`,
    );
  }
  lines.push("");

  return {
    review: "exposure_review.v1",
    markdown: lines.join("\n"),
    summary: s,
    ...(offerHelp
      ? { help: { explain: helpUrl("explain", s.gaps), rollout: helpUrl("rollout", s.gaps), note: HELP_NOTE } }
      : {}),
    ...(s.gaps > 0 ? { sign_up_url: REVIEW_SIGN_UP_URL } : {}),
  };
}

// ---------------------------------------------------------------------------
// MCP registration
// ---------------------------------------------------------------------------

const MAX_FILES = 100;
const MAX_FILE_BYTES = 256 * 1024;

export function registerExposureReviewTool(server: McpServer, rateLimitOk: (tool: string) => boolean): void {
  server.registerTool(
    "atlasent_exposure_review",
    {
      title: "Authorization Exposure Review (free, readable)",
      description:
        "The free Authorization Exposure Review: a readable Markdown review of which CI steps can change real " +
        "systems (deploys, publishes, migrations, infrastructure applies) without an approval gate that can stop " +
        "them, with the exact fix for each and what the review cannot see. Same analysis as " +
        "atlasent_evidence_gap_report, written for a person. Read the repository's .github/workflows/*.yml files and " +
        "pass each one's path and full text as `workflows`. Offline and read-only: no network call, no API key. " +
        "Show the returned `markdown` to the user as is.",
      inputSchema: z.object({
        workflows: z
          .array(
            z.object({
              path: z.string().min(1).max(512).describe("File path, e.g. .github/workflows/deploy.yml"),
              content: z.string().max(MAX_FILE_BYTES).describe("Full text of the workflow file."),
            }),
          )
          .max(MAX_FILES)
          .describe("Every workflow file to review. Omitting files leaves gaps unreported."),
        gate_actions: z
          .array(z.string().min(1).max(256))
          .max(20)
          .optional()
          .describe("Optional `uses:` values that are your own AtlaSent gate wrappers."),
      }),
      annotations: { readOnlyHint: true, destructiveHint: false, openWorldHint: false },
    },
    async (args) => {
      if (!rateLimitOk("atlasent_exposure_review")) {
        return {
          ...toolResult({ error: "rate_limit_exceeded", message: "MCP tool rate limit exceeded — slow down and retry" }),
          isError: true as const,
        };
      }
      const review = renderExposureReview(analyzeWorkflows(args.workflows, args.gate_actions ?? []));
      process.stderr.write(
        JSON.stringify({
          ts: new Date().toISOString(),
          event: "exposure_review.rendered",
          workflows: args.workflows.length,
          gaps: review.summary.gaps,
        }) + "\n",
      );
      return toolResult(review as unknown as Record<string, unknown>);
    },
  );
}
